### PR TITLE
#166354540 Add build and coverage badges to the README file

### PR DESCRIPTION
**Pull request by Emmanuel-Dominic**
#### What does this PR do?
- [x] Add build and coverage badges to the README file

#### Description of Task to be completed?
- [x] This is required to automatically run tests and other preliminary build steps required to ship the next iteration of the product
- [x] Added code quality badge for estimating the quality of Code

#### What are the relevant pivotal tracker stories?
[#166354540](https://www.pivotaltracker.com/n/projects/2350327/stories/166354540)

#### Screenshots
Screenshot 2019-05-31 at 10 57 12

### CODE REVIEW

**Comment by Manorlds-Eaglespark** [comment]
Well done @Emmanuel-Dominic , Kindly add the title of the application on the readme so users know straight away which application they are interfacing with. Thanks.
Screenshot 2019-05-31 at 11 29 13

**Comment by Rhytah** [comment]
> Well done @Emmanuel-Dominic , Kindly add the title of the application on the readme so users know straight away which application they are interfacing with. Thanks.
> Screenshot 2019-05-31 at 11 29 13

@Emmanuel-Dominic Nice work with the badges, just as @Manorlds-Eaglespark has pointed out,  add the project title to `README` and while you are at it you can edit the installation settings to match what actually works for instance `invoke create_settings` to `invoke create-settings`. This will make the `README` more suited for the successful and smooth project set up.

**Review by reifred — APPROVED** [review]
Thanks for the work done @Emmanuel-Dominic. Just work on a few requested changes by @Rhytah and @Manorlds-Eaglespark. In addition, I would suggest you notify others on the new required packages in the requirements.txt file.

**Review by Rhytah — APPROVED** [review]
@Emmanuel-Dominic I can witness that all suggested feedback was worked upon. Great job.

**Review by Manorlds-Eaglespark — APPROVED** [review]

**Pull request merged**
